from Base.Repository.register import register_default_connection, register_base_module_connection, register_async_connections

# 注册默认连接 和 Base模块连接
register_default_connection()
register_base_module_connection()
register_async_connections()